name: Frontend Build and Deploy

on:
  push:
    tags:
      - 'v*.*.*' # Push events to matching v*.*.* tags

jobs:
  build_and_deploy_job:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Specify your Node.js version

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./apps/frontend

      - name: Build the app
        run: yarn workspace frontend build
        working-directory: ./apps/frontend

      - name: Zip build files
        run: zip -r build.zip .next
        working-directory: ./apps/frontend

      - name: Upload zipped build to Azure
        uses: Azure/static-web-apps-deploy@v1
        id: deploy
        with:
          action: "upload"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_WAVE_0F9BACA10  }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: "./apps/frontend/build.zip"   # Zipped file location
          output_location: ".next"                    # Unzip location
          skip_app_build: true
          skip_api_build: true
