name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # 2. Setup Node.js 20
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      # 3. Install Dependencies
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      # 4. Build the Next.js Application
      - name: Build Frontend
        run: yarn workspace frontend build
        # Ensure that your frontend workspace has a 'build' script in its package.json

      # 5. Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_TREE_0A9605800 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e., PR comments)
          action: "upload"
          app_location: "./apps/frontend"            # Path to your Next.js app
          output_location: "./apps/frontend/.next"   # Path to the build output
          skip_app_build: true                        # Skip Azure's build since we've already built it
          skip_api_build: true                        # Skip API build if you have no APIs

