name: Frontend Release

on:
    push:
        branches:
            - main
        paths:
            - "apps/frontend/**"
            - "yarn.lock"
            - ".github/workflows/**"

jobs:
    build_and_deploy_job:
        runs-on: ubuntu-latest
        name: Build and Deploy Job

        steps:
            # 1. Checkout the repository
            - name: Checkout Repository
              uses: actions/checkout@v3

            # 2. Setup Node.js 20
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"
                  cache: "yarn"

            # 3. Install Dependencies
            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            # 4. Build the Next.js Application
            - name: Build Frontend
              working-directory: ./apps/frontend
              run: yarn workspace frontend build

            # 5. Verify Build Output
            - name: Verify Build Output
              run: ls -la ./apps/frontend/out

            # 6. Deploy to Azure Storage Account
            - name: Deploy to Azure Storage Account
              uses: azure/CLI@v1
              with:
                inlineScript: |
                    az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
                    az storage blob upload-batch \
                      --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
                      --source ./apps/frontend/out \
                      --destination '$web'
